spring:
  application.name: poc--languajes-java-spring
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    ROOT: INFO